.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MFFM-LIBSNDFILEW 1 "November 18, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mffm-libsndfilew \- 'C' header to wrap libsndfile in easy to use functions
.SH SYNOPSIS
.B mffm-libsndfilew
For more information relating to this header file please check the documentation. On debian this is located in /usr/share/doc/mffm-libsndfile-dev
.B mffm-libsndfilew
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBmffm-libsndfilew\fP is a header to wrap libsndfile in easy to use functions
.SH OPTIONS
.SH AUTHOR
mffm-libsndfilew was written by Matt R. Flax <flatmax@ieee.org>
.PP
